name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Get binary name
        id: metadata
        run: |
          binary_name=$(cargo metadata --format-version 1 | jq -r '.packages[0].targets | map(select(.kind[] | contains("bin"))) | .[0].name')
          if [ -n "$binary_name" ]; then
            echo "binary_name=$binary_name" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        if: steps.metadata.outputs.binary_name != ''
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary
          path: target/release/${{ steps.metadata.outputs.binary_name }}
